# GitHub workflow to install python 3.9, python libraries from requirements.txt
# and cmdstanpy, then run pytest.

# See here for more about GitHub workflows:
# https://docs.github.com/en/actions/using-workflows

name: Run pytest

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
        matrix:
            os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Set up environment
      run: make env
    - name: Run pytest
      run: source .venv/bin/activate && python -m pytest
